Hexagon dma Transfer Rework patch-1
pranavb-ca/Halide pull request #5
Opened 2017-09-25 14:37 UTC by vgundlur

2017-09-28 11:42 UTC, ronlieb commented on src/runtime/HalideRuntimeHexagonDma.h
> + * CreateContext check if DMA Engines are available
Most of these comment blocks for the prototypes seem redundant, they just take up space and repeat what is already apparent in the prototype. I would suggest replacing the content with a meaningful statement about the function, or removing it all together.

2017-09-28 14:15 UTC, dpalermo commented on src/runtime/hexagon_dma_api.cpp
> + 	cache_mem->desc_region = region_tcm_desc;
line up indentation with code below

2017-09-28 14:16 UTC, dpalermo commented on src/runtime/hexagon_dma_api.cpp
> +	  if (vret == NULL) {
line up indentation with code below...entire function actually needs indent shifted left

2017-09-28 19:43 UTC, pranavb-ca requested changes

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/hexagon_dma_device_interface.cpp
> +    dma_context context;
Any reason you have a public data member?

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/hexagon_dma_api.h
> +typedef DmaContext* dma_context;
Minor nitpick: please consider changing this to
`typedef DmaContext * dma_context_t;`

For some reason, dma_context feels like you are referring to an object, but whereas in fact we are dealign with a pointer.

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/hexagon_dma_api.h
> +typedef struct t_dma_context* dma_context;
Please consider changing the name here.
dma_context makes me think that you are referring to an object of class t_dma_context, but not to a pointer. Please consider dma_context_t or some other such name.

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/hexagon_dma_api.h
> +    dma_context context;
Does this need to be a public member?

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/halide_hexagon_dma_api.cpp
> +    halide_hexagon_dmart_attach_context(user_context, dma_ctxt, (uintptr_t)inframe, fmt, read, \
This function returns an error code. Please catch the error code and return it from here.

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/halide_hexagon_dma_api.cpp
> +    void *vret = halide_hexagon_dma_memory_get(user_context, roi_buf);
Do you think this function will be called from anywhere else? At this point i see that this is the only call site for halide_hexagon_dma_memory_get. If this is going to be the only call-site please consider inlining halide_hexagon_dma_memory_get here. It'll be easier to see what's going on.

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/halide_hexagon_dma_api.cpp
> + * Allocate Memory
Please mention what time of memory is being allocated in the comment here.

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/halide_hexagon_dma_api.cpp
> +        vret = halide_hexagon_dma_memory_alloc(user_context, dma_ctxt, comp, w, h, s, nCircularFold, padding, type);
Please consider rewriting this as
`vret = halide_hexagon_dma_memory_alloc(user_context, dma_ctxt, comp, roi_buf->dim[0].extent,
                                                                          roi_buf->dim[1].extent, roi_buf->dim[1].stride,
                                                                           nCircularFold, padding, type);`

This makes it easy to see what is being passed.

2017-09-28 19:43 UTC, pranavb-ca commented on src/runtime/halide_hexagon_dma_api.cpp
> +    void *vret = halide_hexagon_dma_memory_get(user_context, roi_buf);
Also consider returning early if vret is not null. So consider changing this code to
` halide_assert(user_context, roi_buf != NULL);
   if(roi_buf->host != 0) {
        return (void*) roi_buf->host;
    } else {
     }`

2017-09-30 01:48 UTC, closed without merging

2017-09-30 01:49 UTC, vgundlur commented
Internal review done, will open a PR on Master Branch